### ISSUE TITLE
DRPM v0.1.0

### ISSUE THREAD

**Issue by bnonni** [bnonni/drpm.tools#21]
We got name squatted on npmjs.org (ironic). The new project name is Decentralized Registry Package Manager (DRPM). New vocab and acronyms include 

* Decentralized Registry Package Manager (DRPM) - the combination of DRG and DPM
* Decentralized Registry (DRG) - local registry server to intercept `npm` for installing and publishing DPKs
* Registry Daemon (registryd) - name of the background process the DRG server is running on
* Decentralized Package Manager (DPM) - local package management logic to resolve DPM semver strings to DWN urls

Possible monorepo setup: https://github.com/bnonni/drpm.tools (Backlog)

### Tasks
* [x] Rename anything named with dpm to align with drpm (repo, files and folders)
* [x] Publish v0.1.0 of DRPM
* [x] Do cleanup and reorg

**Comment by bnonni** [comment]
Closign with #23
