### ISSUE TITLE
Module MVP

### ISSUE THREAD

**Issue by bnonni** [bnonni/drpm.tools#3]
* Can be installed into a project and used manually to resolve and install dPacks
* Basic hooks script passed to `node --require ...`
* See [customization-hooks](https://nodejs.org/api/module.html#customization-hooks) for docs about this flag
* Node execution hooks intercepted by the file passed to `--require`, e.g. `node --require register.js index.js`
  * `register.js` registers the core `dpm.js` resolver code
  * `index.js` is your custom code containing DMIs 
* `dpm.js` does the resolving and installing of dPacks

### Tasks
* [x] `register.ts` does the initial registration of the hook for use with `--require`
* [x] `dpm.ts`
  * [x] uses code from [web-features.ts](https://github.com/TBD54566975/web5-js/blob/main/packages/api/src/web-features.ts)
  * [x] intercepts and resolves DMI, resolves DID, gets DWN endpoints, fetches dPack and installs it locally
* [x] `index.ts` exports `dpm.ts`
* [x] publish dpm to npmjs and to dwn as a dPack record

**Comment by bnonni** [comment]
> * Can be installed into a project and used manually to resolve and install dPacks
> * Basic hooks script passed to `node --require ...`
> * See [customization-hooks](https://nodejs.org/api/module.html#customization-hooks) for docs about this flag
> * Node execution hooks intercepted by the file passed to `--require`, e.g. `node --require register.js index.js`
>   
>   * `register.js` registers the core `dpm.js` resolver code
>   * `index.js` is your custom code containing DMIs
> * `dpm.js` does the resolving and installing of dPacks
> 
> ### Tasks
> * [x]  `register.ts` does the initial registration of the hook for use with `--require`
> * [x]  `dpm.ts`
>   
>   * [x]  uses code from [web-features.ts](https://github.com/TBD54566975/web5-js/blob/main/packages/api/src/web-features.ts)
>   * [x]  intercepts and resolves DMI, resolves DID, gets DWN endpoints, fetches dPack and installs it locally
> * [x]  `index.ts` exports `dpm.ts`
> * [x]  publish dpm to npmjs and to dwn as a dPack record

For revised direction, see comments on #2. Closing issue with today's publish to npmjs.com
